"""Assemble canonical docs and saved notebooks for Zensical, without live execution.

The staging tree mirrors repository paths, so ordinary relative Markdown links
work both on GitHub and in the site. Only notebook links change to rendered pages.
"""

from __future__ import annotations

import argparse
import importlib
import re
import subprocess
import sys
import time
from pathlib import Path

import render_registry

from usdata.registry import Registry

ROOT = Path(__file__).resolve().parents[1]
STAGE = ROOT / ".build/docs"
# Only local inline Markdown notebook links; remote links and code remain intact.
NOTEBOOK_LINK = re.compile(r"(\]\()((?![a-zA-Z][\w+.-]*:)[^\s()]+)\.ipynb([#?][^\s()]*)?(\))")


def notebook_links(text: str) -> str:
    return NOTEBOOK_LINK.sub(r"\1\2.md\3\4", text)


def source_paths() -> list[Path]:
    paths = [
        ROOT / name
        for name in ("README.md", "CONTRIBUTING.md", "CHANGELOG.md", "SECURITY.md", "LICENSE")
    ]
    for directory in ("docs", "examples"):
        paths.extend(
            path
            for path in (ROOT / directory).rglob("*")
            if path.is_file()
            and path.suffix in {".md", ".ipynb", ".yaml", ".png", ".svg", ".css"}
            and ".ipynb_checkpoints" not in path.parts
        )
    return sorted(paths)


def prepare() -> None:
    import nbformat
    from nbconvert import MarkdownExporter

    outputs: dict[Path, bytes] = {}
    exporter = MarkdownExporter()
    for path in source_paths():
        relative = path.relative_to(ROOT)
        if path.suffix == ".ipynb":
            body, resources = exporter.from_notebook_node(
                nbformat.read(path, as_version=4),
                resources={"unique_key": path.stem, "output_files_dir": f"{path.stem}_files"},
            )
            body = notebook_links(body)
            body = (
                f"> Saved notebook output; this documentation build does not execute cells. "
                f"[Download the notebook]({path.name}).\n\n" + body
            )
            outputs[relative.with_suffix(".md")] = body.encode()
            for name, data in resources.get("outputs", {}).items():
                outputs[relative.parent / name] = data
            outputs[relative] = path.read_bytes()
        elif path.suffix == ".md":
            outputs[relative] = notebook_links(path.read_text()).encode()
        else:
            outputs[relative] = path.read_bytes()
    for path, content in importlib.reload(render_registry).render_all(Registry.bundled()).items():
        outputs[path.relative_to(ROOT)] = content.encode()
    cli = subprocess.run(
        [sys.executable, "-m", "typer", "usdata.cli.app", "utils", "docs", "--name", "usdata"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    outputs[Path("docs/generated/cli.md")] = (
        "<!-- Generated by scripts/docs_site.py from the Typer app; do not edit. -->\n"
        "# CLI reference\n\nGenerated from the current CLI. "
        "See the [fetch guide](../guides/fetch-and-analyze.md) for workflows.\n\n" + cli
    ).encode()
    for relative, data in outputs.items():
        target = STAGE / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_bytes() != data:
            target.write_bytes(data)
    for path in STAGE.rglob("*"):
        if path.is_file() and path.relative_to(STAGE) not in outputs:
            path.unlink()
    print(f"Prepared {len(outputs)} documentation files from canonical sources", flush=True)


def fingerprint() -> list[tuple[str, int]]:
    paths = source_paths() + list((ROOT / "src").rglob("*.py"))
    paths += [ROOT / "src/usdata/data/registry.yaml", ROOT / "pyproject.toml"]
    paths += list((ROOT / "scripts").glob("*.py"))
    return [(str(path), path.stat().st_mtime_ns) for path in sorted(paths)]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["prepare", "build", "serve"])
    args = parser.parse_args()
    prepare()
    if args.command == "prepare":
        return
    if args.command == "build":
        subprocess.run(
            [sys.executable, "-m", "zensical", "build", "--clean", "--strict"], cwd=ROOT, check=True
        )
        return
    before = fingerprint()
    server = subprocess.Popen(
        [sys.executable, "-m", "zensical", "serve", "--dev-addr", "127.0.0.1:8000"], cwd=ROOT
    )
    try:
        while server.poll() is None:
            time.sleep(0.5)
            after = fingerprint()
            if after != before:
                prepare()
                before = after
    except KeyboardInterrupt:
        pass
    finally:
        server.terminate()
        server.wait()
    if server.returncode not in (0, -2, -15):
        sys.exit(server.returncode)


if __name__ == "__main__":
    main()
